name: CI

on:
  push:
    branches: [ main ]

jobs:
  deploy_github_pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Deploy
        env:
          GH_TOKEN: ${{secrets.PAT_FOR_ACTION}}
        run: npm run deploy
  
  deploy_azure_web_app:
    needs: deploy_github_pages
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          git clone https://github.com/Nukgnaw/nukgnaw.github.io.git
          cd nukgnaw.github.io
          az webapp up --location eastasia --name nukgnaw --html