name: Github Pages/Azure App Service CI/CD

on:
  push:
    branches: [ main ]
    paths-ignore: 
      - 'README.md'
      - '.gitignore'
      - 'LICENSE'

jobs:
  deploy_github_pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.PAT_FOR_ACTION }}
          TARGET_REPO: nukgnaw/nukgnaw.github.io
          TARGET_BRANCH: main
          BUILD_SCRIPT: yarn && yarn build
          BUILD_DIR: blog/.vuepress/dist/
  
  deploy_azure_web_app:
    needs: deploy_github_pages
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: |
            git clone https://github.com/Nukgnaw/nukgnaw.github.io.git
            cd nukgnaw.github.io
            az webapp up --location eastasia --name nukgnaw --html